management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    admin:
      enabled: true

  security:
    user:
      name: admin
      password: admin

  boot:
    admin:
      client:
        username: admin
        password: admin
        url: "http://localhost:8080"
        instance:
          metadata:
            user:
              name: admin
              password: admin